### ISSUE TITLE
Tracking: EIP Implementation

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/alphanet#1]
This issue tracks the existing EIPs we want to include in alphanet. This will grow over time

## Alphanet EVM config
These can be implemented solely in the EVM trait implementation, following this example:
https://github.com/paradigmxyz/reth/blob/main/examples/custom-evm/src/main.rs

### EIP-7212
Spec: https://eips.ethereum.org/EIPS/eip-7212

Example implementation:
https://github.com/alessandromazza98/revm/tree/eip-7212

This is a single precompile, so it will be used in the EVM config implementation 
 - [x] #4

### EIP-3074
Spec: https://eips.ethereum.org/EIPS/eip-3074

Implementation as foundry project with revm patches: https://github.com/anna-carroll/3074

This consists of two instructions, `AUTH` and `AUTHCALL`, also to be set in the EVM config implementation
- [x] #5

### EIP-4337
This involves an alt mempool, requires extra infrastructure, and new RPC endpoints.

Alchemy has a reth-based bundler here: https://github.com/alchemyplatform/rundler

**Comment by onbjerg** [comment]
Closing this since we implemented all the relevant EIPs for season 0
