### ISSUE TITLE
Add alphanet consensus impl

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/alphanet#108]
similar to 

https://github.com/paradigmxyz/reth/blob/7df7bc2c1a83df550c24e3f4a26c067c4690b9eb/crates/optimism/consensus/src/lib.rs#L28-L35

but slightly modified `validate_block_pre_execution` that skips prague checks

https://github.com/paradigmxyz/reth/blob/7df7bc2c1a83df550c24e3f4a26c067c4690b9eb/crates/optimism/consensus/src/lib.rs#L122-L124

**Comment by onbjerg** [comment]
Not really needed since changes to op consensus in reth
