### ISSUE TITLE
`GasSponsoredInvoker` is critically vulnerable

### ISSUE THREAD

**Issue by anna-carroll** [paradigmxyz/alphanet#55]
`to, data` is not checked against the signed `commit`, so if a user signs any `commit`, a caller can pass in / execute arbitrary calls 

**code**: https://github.com/paradigmxyz/alphanet/blob/main/crates/testing/resources/eip3074/src/GasSponsorInvoker.sol

---
Note: i'm assuming this wasn't built to be deployed, just heads up

**Comment by fgimenez** [comment]
@anna-carroll thanks for raising this! you are right, the contracts here are used only in the integration tests, not meant to be deployed. in any case ideas to fix the issue are very welcome :)

**Comment by anna-carroll** [comment]
@fgimenez started a PR demonstrating the fix, I just haven't figured out how to re-build the Solidity in this repo yet (need the updated abi to make the `sol!` macro work)

**Comment by anna-carroll** [comment]
alternative uglier solution would be to leave the function signature the same & add 
```
        require(commit == keccak256(abi.encode(to, data), "Invalid commit");
```
but nevertheless, would like to build & run tests to validate the fix 😅

**Comment by fgimenez** [comment]
> @fgimenez started a PR demonstrating the fix, I just haven't figured out how to re-build the Solidity in this repo yet (i tweaked the function signature and need the updated abi to make the `sol!` macro work)

yep, you can rebuild the artifacts with `make build-eip3074-bytecode`, I'll open a PR to include this in the README
