### ISSUE TITLE
bug: `AUTH` opcode should unset and push0 if authority account has code

### ISSUE THREAD

**Issue by enitrat** [paradigmxyz/alphanet#58]
From [EIP 3074](https://eips.ethereum.org/EIPS/eip-3074#auth-0xf6):

> `authority` is the address of the account which generated the signature. If `EXTCODESIZE` of `authority` is not zero, consider the operation unsuccessful and unset `authorized`.

What I understand from this:
- After loading the account, check the code size
  - If not 0, unset `authorized`, push 0, stop executing the logic of `AUTH` and continue the execution of the current frame.
  
Which means that here we should add something like (pseudocode)

```rust
if acc.code.len() != 0 {
   push_stack(0);
   ctx.remove(AUTHORIZED_VAR_NAME);
   return;
}
```
https://github.com/paradigmxyz/alphanet/blob/008524c84f044c0463ca692b0eca96dc15f64c78/crates/instructions/src/eip3074.rs#L170-L176  
  
I'd be glad to PR this if approved :)

**Comment by mattsse** [comment]
> If EXTCODESIZE of authority is not zero, consider the operation unsuccessful and unset authorized.

I see, so we're lacking a check for this @fgimenez ?
should be easy to add this by checking the account's codehash against KECCAK_EMPTY

**Comment by Rjected** [comment]
yeah, we need the check, although I'm not sure whether we should push 0 to the stack, or just set `instruction_result` to `Stop`

**Comment by enitrat** [comment]
It should push 0 as per @lightclients ' comment https://twitter.com/lightclients/status/1779900806990270773

**Comment by fgimenez** [comment]
@enitrat thanks for the report! should be fixed here https://github.com/paradigmxyz/alphanet/pull/59 PTAL
