### ISSUE TITLE
General project questions

### ISSUE THREAD

**Issue by FabijanC** [paradigmxyz/alphanet#73]
I've been researching Reth AlphaNet a bit. Thanks for the effort so far!

1. My impression is that it is basically Reth with optimism flag enabled and three EIPs supported. Is that correct?
2. What about the sequencer? Is the `alphanet` command somehow planned to also spawn one? In [this documentation paragraph](https://github.com/paradigmxyz/alphanet/?tab=readme-ov-file#running-the-alphanet-execution-node) it's marked with `TODO`:
    ```
   alphanet node
     --chain etc/alphanet-genesis.json \
     --rollup.sequencer-http <TODO> \
     ...
    ```
3. I'm curious if it can in any way be of use to non-EVM experimenting; or am I completely missing the point?

Sorry if this is not the right place to ask, I thought I'd get the quickest answer here.

**Comment by Rjected** [comment]
> My impression is that it is basically Reth with optimism flag enabled and three EIPs supported. Is that correct?

Yes!

> What about the sequencer? Is the alphanet command somehow planned to also spawn one?

Eventually yes, we do not have one now but will in the future

> I'm curious if it can in any way be of use to non-EVM experimenting; or am I completely missing the point?

Ultimately alphanet is still evm based, so that existing languages, smart contract tooling, and knowledge are applicable. Other VMs could be included as a precompile for example if there is any demand! What were you thinking of?

**Comment by FabijanC** [comment]
Thanks for the reply!

> Other VMs could be included as a precompile for example if there is any demand! What were you thinking of?

Starknet (Cairo-based).

**Comment by Rjected** [comment]
> Starknet (Cairo-based).

cool! I think this would have to be implemented as a precompile as mentioned, since the alphanet evm is not intended to be replaced. But it seems possible, and even doable as a variant of alphanet
